spring.data.mongodb.uri=mongodb+srv://pulahruvedant9_db_user:9a8TBIwHUbsJ2Uuc@cluster0.9z47yuu.mongodb.net/?appName=Cluster0

spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true


